build-job:
  stage: build
  image: openjdk:17
  script:
    - |
      echo "Build is going to proceed with the next Java:"
      java -version
      echo "Gradle Wrapper:"
      ./gradlew -v
      echo "Current directory state:"
      ls -la
      ./gradlew buildPlugin
      cd build/distributions
      ZIP_NAME_WITH_EXT=`ls *.zip`
      unzip "$ZIP_NAME_WITH_EXT" -d content
      mv content/* ../../built-plugin
  artifacts:
    name: "for-mainframe-private"
    paths:
      - built-plugin/
    expire_in: 4 weeks

test-job:
  stage: test
  image: openjdk:17
  dependencies:
    - build-job
  script:
    - |
      echo "Test is going to proceed with the next Java:"
      java -version
      echo "Gradle Wrapper:"
      ./gradlew -v
      echo "Current directory state:"
      ls -la
    - ./gradlew test
    - mv build/reports/tests junit-report
    - mv build/reports/kover/html kover-report
  artifacts:
    name: "for-mainframe-test-results"
    paths:
      - junit-report/
      - kover-report/
    reports:
      junit: build/test-results/test/*.xml
    expire_in: 4 weeks
