# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout of github repository
      uses: actions/checkout@v3

    - name: Setup of environment
      uses: ./.github/actions/setup

    - name: Check repository content
      shell: bash
      run: pwd && ls -la

    - name: Cache Gradle packages
      uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: ${{ runner.os }}-gradle

    - name: Build with Gradle
      run: ./gradlew buildPlugin
      shell: bash

    # - name: Run tests
    #   run: ./gradlew test
    #   shell: bash

    # - name: Sonarcloud scans
    #   uses: ./.github/actions/sonar
    #   env:
    #     SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
    #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    #     GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}

    - name: Get name of the built plugin archive
      id: getting_file_name
      shell: bash
      run: >
        CURRENT_FILE_PATH=$(echo $(find build -name "for-mainframe*.zip")) &&
        echo "CURRENT_FILE_PATH=$CURRENT_FILE_PATH" >> $GITHUB_ENV &&
        echo "Name of current file: $CURRENT_FILE_PATH"

    - name: Prepare signed plugin version
      env:
        PUBLISH_TOKEN: ${{ secrets.INTELLIJ_SIGNING_PUBLISH_TOKEN }}
        CERTIFICATE_CHAIN: ${{ secrets.INTELLIJ_SIGNING_CERTIFICATE_CHAIN }}
        PRIVATE_KEY: ${{ secrets.INTELLIJ_SIGNING_PRIVATE_KEY }}
        PRIVATE_KEY_PASSWORD: ${{ secrets.INTELLIJ_SIGNING_PRIVATE_KEY_PASSWORD }}
      run: ./gradlew signPlugin

    - name: Publish built plugin to artifacts
      uses: actions/upload-artifact@v3
      with:
        name: $CURRENT_FILE_PATH
        path: ./build/distributions/
