# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  workflow_dispatch:

permissions:
  contents: read


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout of github repository
      uses: actions/checkout@v3
    - name: Setup of environment
      uses: ./.github/actions/setup
    - name: Check repopository content
      run: pwd && ls -la
      shell: bash
    - name: Cache Gradle packages
      uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: ${{ runner.os }}-gradle
    - name: Build with Gradle
      run: gradle wrapper && ./gradlew buildPlugin
      shell: bash
#    - name: Sonarcloud scans
#      uses: ./.github/actions/sonar
    - name: Cache SonarCloud packages
      uses: actions/cache@v1
        with:
          path: ~/.sonar/caches
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
    - name: Code coverage and publish results
      run: >
        ./gradlew --info sonarqube
        -Dorg.gradle.jvmargs="-XX:MaxMetaspaceSize=512m"
        -Dresults="build/reports/tests/test,build/test-results/test,build/reports/jacoco/test/html"
        -Psonar.host.url=$SONAR_HOST_URL -Dsonar.login=$SONAR_TOKEN
        -Partifactory_user=$ARTIFACTORY_USERNAME -Partifactory_password=$ARTIFACTORY_PASSWORD
        -Dsonar.coverage.jacoco.xmlReportPaths="build/reports/jacoco.xml"
      env:
        ARTIFACTORY_USE RNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
        ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
